environment:
  nugetversion: 1.0.0 #This version is leading

version: $(nugetversion).build{build} 

configuration: Release

os: Visual Studio 2017

before_build:
  - nuget restore

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

build:
  publish_nuget: true 

skip_tags: true

clone_depth: 1

dotnet_csproj:
  patch: true
  file: '**\Selenium.Community.PageObjects.csproj'
  version: '$(nugetversion)'
  package_version: '$(nugetversion)'
  assembly_version: '$(nugetversion)'
  file_version: '$(nugetversion)'
  informational_version: '$(nugetversion)'

skip_commits:
  files:
  - README.md

deploy:
  provider: NuGet
  on:
    branch: master
  server:                     
  api_key:
    secure: fJFLKVGeErCKif3KJLKoAzH2kKgfl3lJxNUVrRJzAsUo3yMkLUTdRuvWTSnRSLPQ
  skip_symbols: false
  symbol_server:           
  artifact: /.*\.nupkg/