version: 0.1.{build}

configuration: Release

os: Visual Studio 2017

before_build:
  - nuget restore

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

skip_tags: true

clone_depth: 1

test: off
