version: 1.0.{build}

configuration: Release

os: Visual Studio 2017

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

skip_tags: true

clone_depth: 1

test: off

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MyGet
