version: 0.1.{build}-alpha

configuration: Release

os: Visual Studio 2017

before_build:
  - nuget restore

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

build:
  publish_nuget: true 

skip_tags: true

clone_depth: 1

deploy:
  provider: NuGet
  on:
    branch: master
  server:                     
  api_key:
  secure: gU55bWD2Ech9rRqMtBDzGEppTTNUvRwW1H3rP1XucIlxmOEkEqajwqNUE39HfEz6
  skip_symbols: false
  symbol_server:           
  artifact: /.*\.nupkg/