version: 0.1.{build} #This version is leading

configuration: Release

os: Visual Studio 2017

before_build:
  - nuget restore

nuget:
  disable_publish_on_pr: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

build:
  publish_nuget: true 

skip_tags: true

clone_depth: 1

dotnet_csproj:
  patch: true
  file: '**\Selenium.Community.PageObjects.csproj'
  version: '{version}-alpha'
  package_version: '{version}-alpha'
  assembly_version: '{version}'
  file_version: '{build}'
  informational_version: '{version}'

skip_commits:
  files:
  - README.md

deploy:
  provider: NuGet
  on:
    branch: master
  server:                     
  api_key:
    secure: fJFLKVGeErCKif3KJLKoAzH2kKgfl3lJxNUVrRJzAsUo3yMkLUTdRuvWTSnRSLPQ
  skip_symbols: false
  symbol_server:           
  artifact: /.*\.nupkg/